
(sum(CASE
  WHEN 
    Fdate BETWEEN DATETIME_SUB(TODAY(), INTERVAL 8 DAY) AND DATETIME_SUB(TODAY(), INTERVAL 1 DAY)
    THEN if(ENDS_WITH(Fname,task-id),fspent,0)
  ELSE 0
END)

+

sum(CASE
  WHEN 
    ldate BETWEEN DATETIME_SUB(TODAY(), INTERVAL 8 DAY) AND DATETIME_SUB(TODAY(), INTERVAL 1 DAY)
    THEN if(ENDS_WITH(lname,task-id),lspent,0)
  ELSE 0
END)

+

sum(CASE
  WHEN 
    pdate BETWEEN DATETIME_SUB(TODAY(), INTERVAL 8 DAY) AND DATETIME_SUB(TODAY(), INTERVAL 1 DAY)
    THEN if(ENDS_WITH(Pname,task-id),pspent,0)
  ELSE 0
END)

+

sum(CASE
  WHEN 
    gdate BETWEEN DATETIME_SUB(TODAY(), INTERVAL 8 DAY) AND DATETIME_SUB(TODAY(), INTERVAL 1 DAY)
    THEN if(ENDS_WITH(Gname,task-id),gspent,0)
  ELSE 0
END)
)/7